name: "Pull Request - Main"

on:
  pull_request:
    branches:
      - main
    

jobs:
  lint:
    environment: prod
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
        continue-on-error: true
  test:
    environment: prod
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
        continue-on-error: true
  build:
    environment: prod
    name: "Build"
    runs-on: ubuntu-latest
    # needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

        env:  EMAIL_PUBLIC_KEY: ${{ secrets.EMAIL_PUBLIC_KEY }}
         EMAIL_SERVICE_ID: ${{ secrets.EMAIL_SERVICE_ID }}
         EMAIL_TEMPLATE_ID: ${{ secrets.EMAIL_TEMPLATE_ID }}


